# ref: http://docs.travis-ci.com/user/build-configuration

language: erlang

env:
    global:
        - DEPS_BUILD_DIR=$TRAVIS_BUILD_DIR/deps
        - LJ_REPO="https://github.com/LuaJIT/LuaJIT.git"
        - INC_DIR=/usr/local/include
    matrix:
        - LUA=lua-5.1    LUA_TYPE=lua    LUA_BIN=lua     LUA_DIST=lua-5.1.5      LUA_BD=lua    LUA_INC=$INC_DIR
        - LUA=lua-5.2    LUA_TYPE=lua    LUA_BIN=lua     LUA_DIST=lua-5.2.4      LUA_BD=lua    LUA_INC=$INC_DIR
        - LUA=lua-5.3    LUA_TYPE=lua    LUA_BIN=lua     LUA_DIST=lua-5.3.2      LUA_BD=lua53  LUA_INC=$INC_DIR
        - LUA=luajit-2.0 LUA_TYPE=luajit LUA_BIN=luajit             LJ_BR=master LUA_BD=lua    LUA_INC=$INC_DIR/$LUA
        - LUA=luajit-2.1 LUA_TYPE=luajit LUA_BIN=luajit-2.1.0-beta1 LJ_BR=v2.1   LUA_BD=lua    LUA_INC=$INC_DIR/$LUA

before_install:
    - mkdir -p $DEPS_BUILD_DIR
    - sudo apt-get update -qq
    - sudo apt-get install libprotobuf-dev protobuf-compiler

install:
    # install Lua/LuaJIT
    - cd $DEPS_BUILD_DIR
    - if [ "$LUA_TYPE" == "luajit" ]; then
          git clone -b $LJ_BR $LJ_REPO luajit2.git && cd luajit2.git && sudo make install;
      fi
    - if [ "$LUA_TYPE" == "lua" ]; then
          wget "http://www.lua.org/ftp/$LUA_DIST.tar.gz" && tar xzf $LUA_DIST.tar.gz && cd $LUA_DIST && sudo make linux test install;
      fi
    # build lib
    - cd $TRAVIS_BUILD_DIR
    - make
    # build lib bindings
    - make -C binding/$LUA_BD LUADIR=$LUA_INC

before_script:
    # back to home directory
    - cd $TRAVIS_BUILD_DIR
    # check executables
    - which $LUA_BIN 2>/dev/null && $LUA_BIN -v

script:
    - cd $TRAVIS_BUILD_DIR/binding/$LUA_BD
    - $LUA_BIN test.lua

notifications:
    email:
        on_success: change
        on_failure: always
